services:
  - type: web
    name: springboot-app
    env: java
    plan: free
    buildCommand: |
      chmod +x mvnw
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/MyApp-0.0.1-SNAPSHOT.jar
